apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cities.london.io
spec:
  group: london.io
  version: v1alpha1
  scope: Namespaced
  names:
    plural: cities
    singular: city
    kind: City
    shortNames:
    - ci
